int64 id
int64 musn_id
string musn_name
string concert_name
string concert_date
int64 quantity
int64 price
int64 duration
---
int64 sale_count
int64 revenue
---
int64 sale_count
int64 revenue
int64 remng_duration